language: php

php:
  - 5.6

services:
  - mysql
  - redis-server

install:
  - composer install --prefer-dist --no-interaction
  - bin/reload test

script:
  - bin/phpunit -c app
  - bin/behat -fprogress
  - app/console security:check
