language: php

php:
  - 5.6

services:
  - mysql
  - redis-server

install:
  - composer install --prefer-dist --no-interaction
  - cp app/Resources/views/admin.dist.html.twig app/Resources/views/admin.html.twig
  - cp app/Resources/views/base.dist.html.twig app/Resources/views/base.html.twig
  - bin/reload test

script:
  - bin/phpunit -c app
  - bin/behat -fprogress
  - app/console security:check
