---
- name: install supervisor
  yum: name=supervisor state=latest
  tags: [ supervisor ]

- name: ensure supervisord is started
  service: name=supervisord enabled=yes state=started
  tags: [ supervisor ]

