---
# - name: get epel supervisor centos 6
#   get_url: dest=/etc/yum.repos.d/epel-supervisor.repo url=http://repos.fedorapeople.org/repos/rmarko/supervisor/epel-supervisor.repo
#   tags: [ supervisor ]

- name: install supervisor
  yum: name=supervisor state=latest
  tags: [ supervisor ]

- name: ensure supervisord is started
  service: name=supervisord enabled=yes state=started
  tags: [ supervisor ]

