services:
  api.response.listener:
    class: ApiBundle\EventListener\ApiResponseListener
    arguments: [%kernel.environment%, "@translator", "@?logger"]
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 10}
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
      - { name: kernel.event_listener, event: kernel.view, method: onKernelView }
