imports:
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: service_aliases.yml }

framework:
  translator:
    fallback: "%locale%"
  secret: "%secret%"
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  form: ~
  csrf_protection: ~
  validation:
    enable_annotations: true
  templating:
    engines: ['twig']
  default_locale:  "%locale%"
  trusted_hosts: ~
  trusted_proxies: ~
  session:
    save_path: null # use default php.ini settings if storage is file
    cookie_lifetime: 3600 # note php setting: session.gc_maxlifetime
    cookie_domain: ~ # restrict to specific domain
    cookie_secure: false # allow only https
    cookie_httponly: false # allow only http protocol access
  fragments: ~
  http_method_override: true
  assets:
    version: %asset_version%

twig:
  debug: "%kernel.debug%"
  strict_variables: true
  form_themes:
    - "AppBundle::forms.html.twig" # default bootstrap3 horizontal form theme

doctrine:
  dbal:
    driver:   "%database_driver%"
    host:     "%database_host%"
    port:     "%database_port%"
    dbname:   "%database_name%"
    user:     "%database_user%"
    password: "%database_password%"
    charset:  UTF8

  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true

doctrine_migrations:
  dir_name: %kernel.root_dir%/../src/AppBundle/Migration
  namespace: AppBundle\Migration
  table_name: app_migrations
  name: App migrations

swiftmailer:
  transport: "%mailer_transport%"
  host:      "%mailer_host%"
  username:  "%mailer_user%"
  password:  "%mailer_password%"
  auth_mode: "%mailer_auth_mode%"
  port:      "%mailer_port%"
  spool:     { type: memory }

ewz_recaptcha:
  public_key:  %recaptcha_public_key%
  private_key: %recaptcha_private_key%
  locale_key:  %kernel.default_locale%

knp_menu:
  twig:
    template: "::menu.html.twig"

