admin: {resource: "@AdminBundle/Resources/config/routing.yml", prefix: "admin"}
app: {resource: "@AppBundle/Resources/config/routing.yml"}
api: {resource: "@ApiBundle/Resources/config/routing.yml", prefix: "api"}
