parameters:
  redis_timeout: 5
  redis_db_default: 0
  redis_db_session: 1

services:
  cache.connection.default:
    class: Predis\Client
    arguments:
      - { host: %redis_host%, port: %redis_port%, database: %redis_db_default% }

  cache.connection.session:
    class: Predis\Client
    arguments:
      - { host: %redis_host%, port: %redis_port%, database: %redis_db_session% }

  cache.default:
    class: AppBundle\Cache\RedisCache
    arguments:
      - @cache.connection.default
      - %cache_namespace%

  session.handler.redis:
    class: AppBundle\Cache\Session\RedisSessionHandler
    arguments:
      - @cache.connection.session
