---
# given our server OS is centos, install package repositories
- hosts: all
  sudo: yes
  tasks:
    - name: ensure epel repo present
      yum: pkg=epel-release state=installed

    - name: ensure remi repo present
      yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=installed

# provision and deploy frontends
- hosts: frontends
  roles:
    - { role: user, sudo: yes }
    - { role: mysql, sudo: yes }
    - { role: redis, sudo: yes }
    - { role: php-fpm, sudo: yes }
    - { role: nginx, sudo: yes }
    - { role: skel, sudo: yes, sudo_user: "{{ user }}" }
    - { role: frontend, sudo: yes, sudo_user: "{{ user }}" }
